FILES_PATH := vendor/lge/f460/proprietary

PRODUCT_PACKAGES += \
    libtime_genoff 

PRODUCT_COPY_FILES += \
    $(FILES_PATH)/app/atfwd/atfwd.apk:system/app/atfwd/atfwd.apk \
    $(FILES_PATH)/app/qcrilmsgtunnel/qcrilmsgtunnel.apk:system/app/atfwd/qcrilmsgtunnel.apk \
    $(FILES_PATH)/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    $(FILES_PATH)/bin/cpfirmware:system/bin/cpfirmware \
    $(FILES_PATH)/bin/efsks:system/bin/efsks \
    $(FILES_PATH)/bin/imsdatadaemon:system/bin/imsdatadaemon \
    $(FILES_PATH)/bin/imsqmidaemon:system/bin/imsqmidaemon \
    $(FILES_PATH)/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    $(FILES_PATH)/bin/irsc_util:system/bin/irsc_util \
    $(FILES_PATH)/bin/ks:system/bin/ks \
    $(FILES_PATH)/bin/mdm_helper:system/bin/mdm_helper \
    $(FILES_PATH)/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    $(FILES_PATH)/bin/netmgrd:system/bin/netmgrd \
    $(FILES_PATH)/bin/port-bridge:system/bin/port-bridge \
    $(FILES_PATH)/bin/ptt_socket_app:system/bin/ptt_socket_app \
    $(FILES_PATH)/bin/qcks:system/bin/qcks \
    $(FILES_PATH)/bin/qmuxd:system/bin/qmuxd \
    $(FILES_PATH)/bin/qseecomd:system/bin/qseecomd \
    $(FILES_PATH)/bin/radish:system/bin/radish \
    $(FILES_PATH)/bin/rmnetcli:system/bin/rmnetcli \
    $(FILES_PATH)/bin/smpl_count:system/bin/smpl_count \
    $(FILES_PATH)/bin/time_daemon:system/bin/time_daemon \
    $(FILES_PATH)/bin/wififtmd:system/bin/wififtmd \
    $(FILES_PATH)/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    $(FILES_PATH)/lib/libbcmwl.so:system/lib/libbcmwl.so \
    $(FILES_PATH)/lib/libbluedroid_bdt.so:system/lib/libbluedroid_bdt.so \
    $(FILES_PATH)/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    $(FILES_PATH)/lib/libimsmedia.so:system/lib/libimsmedia.so \
    $(FILES_PATH)/lib/libimsmmpf.so:system/lib/libimsmmpf.so \
    $(FILES_PATH)/lib/libims.so:system/lib/libims.so \
    $(FILES_PATH)/lib/liblgehdcpek.so:system/lib/liblgehdcpek.so \
    $(FILES_PATH)/lib/liblgerft.so:system/lib/liblgerft.so \
    $(FILES_PATH)/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
    $(FILES_PATH)/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    $(FILES_PATH)/lib/libnetmgr.so:system/lib/libnetmgr.so \
    $(FILES_PATH)/lib/libqti_performance.so:system/lib/libqti_performance.so \
    $(FILES_PATH)/lib/librmnetctl.so:system/lib/librmnetctl.so \
    $(FILES_PATH)/lib/libril.so:system/lib/libril.so \
    $(FILES_PATH)/lib/libuicc.so:system/lib/libuicc.so \
    $(FILES_PATH)/lib/libunified_sysfs_pm.so:system/lib/libunified_sysfs_pm.so \
    $(FILES_PATH)/lib/libvss_bsp_qcci.so:system/lib/libvss_bsp_qcci.so \
    $(FILES_PATH)/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
    $(FILES_PATH)/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
    $(FILES_PATH)/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
    $(FILES_PATH)/lib/libvss_dmi_qcci.so:system/lib/libvss_dmi_qcci.so \
    $(FILES_PATH)/lib/libvss_gnss_qcci.so:system/lib/libvss_gnss_qcci.so \
    $(FILES_PATH)/lib/libvss_ims_qcci.so:system/lib/libvss_ims_qcci.so \
    $(FILES_PATH)/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
    $(FILES_PATH)/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
    $(FILES_PATH)/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
    $(FILES_PATH)/lib/libvss_resim_core.so:system/lib/libvss_resim_core.so \
    $(FILES_PATH)/lib/libvss_resim_idl.so:system/lib/libvss_resim_idl.so \
    $(FILES_PATH)/lib/libvss_resim_iface.so:system/lib/libvss_resim_iface.so \
    $(FILES_PATH)/lib/libwvoemprov.so:system/lib/libwvoemprov.so \
    $(FILES_PATH)/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    $(FILES_PATH)/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    $(FILES_PATH)/vendor/firmware/a420_pfp.fw:system/vendor/firmware/a420_pfp.fw \
    $(FILES_PATH)/vendor/firmware/a420_pm4.fw:system/vendor/firmware/a420_pm4.fw \
    $(FILES_PATH)/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(FILES_PATH)/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    $(FILES_PATH)/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(FILES_PATH)/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(FILES_PATH)/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(FILES_PATH)/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(FILES_PATH)/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(FILES_PATH)/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    $(FILES_PATH)/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(FILES_PATH)/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(FILES_PATH)/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(FILES_PATH)/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    $(FILES_PATH)/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(FILES_PATH)/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    $(FILES_PATH)/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(FILES_PATH)/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    $(FILES_PATH)/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(FILES_PATH)/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(FILES_PATH)/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(FILES_PATH)/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(FILES_PATH)/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(FILES_PATH)/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(FILES_PATH)/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(FILES_PATH)/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(FILES_PATH)/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    $(FILES_PATH)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(FILES_PATH)/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    $(FILES_PATH)/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    $(FILES_PATH)/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(FILES_PATH)/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    $(FILES_PATH)/etc/firmware/fw_bcmdhd_mfg.bin:system/etc/firmware/fw_bcmdhd_mfg.bin \
    $(FILES_PATH)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(FILES_PATH)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(FILES_PATH)/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
    $(FILES_PATH)/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
    $(FILES_PATH)/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
    $(FILES_PATH)/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(FILES_PATH)/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(FILES_PATH)/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(FILES_PATH)/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(FILES_PATH)/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(FILES_PATH)/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(FILES_PATH)/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(FILES_PATH)/etc/firmware/vpu.b00:system/etc/firmware/vpu.b00 \
    $(FILES_PATH)/etc/firmware/vpu.b01:system/etc/firmware/vpu.b01 \
    $(FILES_PATH)/etc/firmware/vpu.b02:system/etc/firmware/vpu.b02 \
    $(FILES_PATH)/etc/firmware/vpu.b03:system/etc/firmware/vpu.b03 \
    $(FILES_PATH)/etc/firmware/vpu.b04:system/etc/firmware/vpu.b04 \
    $(FILES_PATH)/etc/firmware/vpu.b05:system/etc/firmware/vpu.b05 \
    $(FILES_PATH)/etc/firmware/vpu.b06:system/etc/firmware/vpu.b06 \
    $(FILES_PATH)/etc/firmware/vpu.b07:system/etc/firmware/vpu.b07 \
    $(FILES_PATH)/etc/firmware/vpu.b08:system/etc/firmware/vpu.b08 \
    $(FILES_PATH)/etc/firmware/vpu.b09:system/etc/firmware/vpu.b09 \
    $(FILES_PATH)/etc/firmware/vpu.b10:system/etc/firmware/vpu.b10 \
    $(FILES_PATH)/etc/firmware/vpu.b11:system/etc/firmware/vpu.b11 \
    $(FILES_PATH)/etc/firmware/vpu.b12:system/etc/firmware/vpu.b12 \
    $(FILES_PATH)/etc/firmware/vpu.mbn:system/etc/firmware/vpu.mbn \
    $(FILES_PATH)/etc/firmware/vpu.mdt:system/etc/firmware/vpu.mdt \
    $(FILES_PATH)/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    $(FILES_PATH)/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml  \
    $(FILES_PATH)/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    $(FILES_PATH)/etc/lgodm/gps.cfg:system/etc/lgodm/gps.cfg \
    $(FILES_PATH)/etc/lgodm/gps_sap_pdr.cfg:system/etc/lgodm/gps_sap_pdr.cfg \

